name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # This will trigger the deployment on any push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This checks out your repository's code

    - name: Set up Node.js (optional)
      uses: actions/setup-node@v2  # This is only needed if you're using a JS build tool or framework

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4  # A pre-made action to deploy to GitHub Pages
      with:
        branch: gh-pages   # The branch to deploy to (GitHub Pages typically uses 'gh-pages')
        folder: .  # The folder to deploy, '.' for the entire project
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
